# Generated by Django 5.0 on 2023-12-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_table_is_reserved_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
        migrations.AddField(
            model_name='table',
            name='last_reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
