# Generated by Django 5.0 on 2023-12-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_table_is_reserved_table_last_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='last_reservation_date',
        ),
    ]
