# Generated by Django 5.0 on 2023-12-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_table_last_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='last_reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
